### ISSUE TITLE
[Fanout Tracking] security-ops - Fully Functional Proxima US Stamp

### ISSUE THREAD

**Issue by justhchung** [github/branch-deploy#347]
### Fanout Effort

https://github.com/github/fanout/issues/2362

### 🚦 Status

|Field|Value
|-----|-----|
|Trending|ready for work|
|Last Report Date||
|Company Priority|Priority 1|

### 🧳 Accountability

|Field|Value
|-----|-----|
|Exec Sponsor|alexiswales
|DRI|@admgc
|Product Area||

### 📅 Key Dates

|Field|Value
|-----|-----|
|Start Date||
|Target Date||

### 🏔 Fanout Summary

In Q2FY25 we went to GA with Proxima (now GHEC with Data Residency) in the EU and soon Australia. In Q3FY25, we are expanding to the United States. In order to do this, we are asking all the teams to be fully functional in the US stamp while considering the effort it takes to stand up stamps while being opportunistic when it comes to automating and simplifying the effort needed to stand up more stamps in the future.

>[!Important]
> The US stamp is the top priority stamp to completed in Q3 FY25. If there are tradeoffs to be made between working on this and the pre-production stamp, choose the US first and communicate impacts to the other stamp progress.

### 📈 Overview of the Requested Work

‼ Infrastructure and core services will be deployed early in Q3FY25 (January) and service teams will be able to start onboarding from mid February 2025. We will communicate the changes in the Fanout issues and in Proxima/Fanout channels when the this stamp are ready for service onboarding. Until then, the Fanout issue status stays inactive.

When this is ready, please follow your playbooks for onboarding to the new stamp.

This stamp is located in `prod-cus-01`. Information on the stamps and the current state can always be found in the [DevPortal](https://devportal.githubapp.com/proxima/stamps).

### 🚦 Success Target

The DRI will provide weekly updates by Wednesday 5 PM PT for each of the Fanout issues.
Updates are submitted in this Fanout issue by calling the ‘/short-report’ issue comment template.

###  📝 Supporting Materials

- [Fully Functional Service Guidance](https://github.com/github/proxima/blob/main/docs/guides/fully%20functional%20service%20guidance.md)
- [New Stamp creation playbook](https://github.com/github/proxima/tree/main/docs/playbooks/new-stamp-creation#new-stamp-creation-playbook)
- [Heaven Pipelines Onboarding](https://thehub.github.com/epd/engineering/devops/deployment/onboarding-to-heaven-pipelines/)
- [Proxima Observability Guidance](https://thehub.github.com/epd/engineering/products-and-services/proxima/observability/)
- For support, there are various `#proxima-*` channels depending on what is needed.
- For help with deployments or pipeline updates come by [#deploy-support](https://github.slack.com/archives/CECRLG4LQ).
- For observability help use [#observability](https://github.slack.com/archives/C9H0UJC2W).
- For tenancy questions stop by [#proxima-tenancy](https://github.slack.com/archives/C02TQDUV4M6).

### ✔️ Tasklist

```[tasklist]
### Tasks
- [ ] Your services are onboarded to pipelines and continuously deploying to Staffship, Dotcom, West EU, Sweden, Australia, and US stamps. It blocks on deployment failures to any stamp.
- [ ] Your services are working as expected in Proxima and does not expose tenant suffixes in UI and API customer facing experiences
- [ ] Your services have completed a bug bash on the Proxima Sweden and Australia stamps, and you’re ready to accept bug reports and resolve bugs per [SLOs](https://github.com/github/engineering/discussions/3484).
- [ ] Your services have metrics, dashboards, and alerting in place for the Proxima US Stamp
- [ ] Any low effort, high ROI automation is implemented
```
