### ISSUE TITLE
[Fanout Tracking] security-ops - Fully Functional Proxima Pre-production Stamp + Secrets Inventory

### ISSUE THREAD

**Issue by justhchung** [github/branch-deploy#348]
### Fanout Effort

https://github.com/github/fanout/issues/2361

### 🚦 Status

|Field|Value
|-----|-----|
|Trending|ready for work|
|Last Report Date||
|Company Priority|Priority 1|

### 🧳 Accountability

|Field|Value
|-----|-----|
|Exec Sponsor|alexiswales
|DRI|@admgc
|Product Area||

### 📅 Key Dates

|Field|Value
|-----|-----|
|Start Date||
|Target Date||

### 🏔 Fanout Summary

With Proxima Public GA launch on October 29 and Billing customers onboarding to Proxima stamps, there is a need for a Pre-production stamp to carry out BCDR and other disruptive testing activities without impacting customers. In order to do this, we are asking the teams to stand up infrastructure and become fully functional in the Pre-production (Canada) stamp. After the Infrastructure of the Pre-production stamp is set up, Service teams can start onboarding to the Pre-production stamp in the second half of FY25 Q3.

As part of setting up the pre-production environment, we need to have this Proxima stamp built and fully functional. Additionally, we want to build a better understanding of the ownership and types of secrets as a part of this Proxima onboarding. More details on this can be found in the supporting documents and task list.

### 📈 Overview of the Requested Work

:bangbang: Infrastructure and core services will be deployed early in Q3FY25 (January) and service teams will be able to start onboarding from mid February 2025. We will communicate the changes in the Fanout issues and in Proxima/Fanout channels when the this stamp are ready for service onboarding. Until then, the Fanout issue status stays inactive.

When this is ready, please follow your playbooks for onboarding to the new stamp.

>[!Important]
>Additionally, teams should complete the secrets inventory task described in the supporting documents and task list below. This task is specific to the pre-production stamp and does not apply to the US stamp at this time.

This stamp is located in `test-cnc-01`. Information on the stamps and the current state can always be found in the [DevPortal](https://devportal.githubapp.com/proxima/stamps).

### 🚦 Success Target

The DRI will provide weekly updates by Wednesday 5 PM PT for each of the Fanout issues.
Updates are submitted in this Fanout issue by calling the ‘/short-report’ issue comment template.

###  📝 Supporting Materials

- [Fully Functional Service Guidance](https://github.com/github/proxima/blob/main/docs/guides/fully%20functional%20service%20guidance.md)
- [New Stamp creation playbook](https://github.com/github/proxima/tree/main/docs/playbooks/new-stamp-creation#new-stamp-creation-playbook)
- [Heaven Pipelines Onboarding](https://thehub.github.com/epd/engineering/devops/deployment/onboarding-to-heaven-pipelines/)
- [Proxima Observability Guidance](https://thehub.github.com/epd/engineering/products-and-services/proxima/observability/)
- For support, there are various #proxima-* channels depending on what is needed.
- For help with deployments or pipeline updates come by [#deploy-support](https://github.slack.com/archives/CECRLG4LQ).
- For observability help use [#observability](https://github.slack.com/archives/C9H0UJC2W).
- For tenancy questions stop by [#proxima-tenancy](https://github.slack.com/archives/C02TQDUV4M6).
- __NEW__ - Config and secrets inventory for the new environment is in the repository as described in [this documentation](https://github.com/github/proxima/blob/main/docs/playbooks/new-stamp-creation/config-and-secrets-in-repo.md)

### ✔️ Tasklist

```[tasklist]
### Tasks
- [ ] Your services are onboarded to pipelines and continuously deploying to Staffship, Dotcom, West EU, Sweden, Australia, and US stamps. It blocks on deployment failures to any stamp.
- [ ] Config and secrets inventory for the new environment is in the repository as described in this [documentation](https://github.com/github/proxima/blob/main/docs/playbooks/new-stamp-creation/config-and-secrets-in-repo.md)
- [ ] Your services are working as expected in Proxima and does not expose tenant suffixes in UI and API customer facing experiences
- [ ] Your services have completed a bug bash on the Proxima Sweden and Australia stamps, and you’re ready to accept bug reports and resolve bugs per [SLOs](https://github.com/github/engineering/discussions/3484).
- [ ] Your services have metrics, dashboards, and alerting in place for the Proxima US Stamp
- [ ] Any low effort, high ROI automation is implemented
